### ISSUE TITLE
Add support for Aerospike as a state store

### ISSUE THREAD

**Issue by patkivikram** [faust-streaming/faust#114]
Add support for aerospike in addition to InMemoryStore and Rocksdb

**Comment by ondrejchmelar** [comment]
It would be worth mentioning this in documentation, I only learned there is a third store option by chance.

https://faust.readthedocs.io/en/latest/userguide/application.html?highlight=store#application-parameters
https://faust.readthedocs.io/en/latest/developerguide/overview.html?highlight=store#store
