### ISSUE TITLE
rocksdb requirement should be updated to faust-streaming-rocksdb

### ISSUE THREAD

**Issue by jkgenser** [faust-streaming/faust#121]
## Checklist

https://github.com/faust-streaming/faust/blob/master/requirements/extras/rocksdb.txt

## Steps to reproduce

Tell us what you did to cause something to happen.

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version
* Faust version
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by taybin** [comment]
Fixed by #168
