### ISSUE TITLE
orjson dependency update

### ISSUE THREAD

**Issue by Roman1us** [faust-streaming/faust#125]
I've got question about orjson version included in master. Сan I update it to the latest version?

## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Tell us what you did to cause something to happen.

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version
* Faust version
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by patkivikram** [comment]
Sure send in a PR and we can validate it

**Comment by taybin** [comment]
@Roman1us this can be closed when #135 is merged in.
