### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by irux** [faust-streaming/faust#128]
Hello, what do you think about changing the name of the project?. I think the word faust bring only confusion with the old repo and it can benefit to "clean" the name of the project.

It is only a preposition.

**Comment by patkivikram** [comment]
what do you suggest?

**Comment by zerafachris** [comment]
FPS - Fast Python Streaming

**Comment by irux** [comment]
pystreams

**Comment by sambott** [comment]
Keller?
The first place Faust went in the play https://en.wikipedia.org/wiki/Auerbachs_Keller

**Comment by taybin** [comment]
Goethe, the writer of Faust.

**Comment by wbarnha** [comment]
I really like the name Goethe and Keller, but I think this project is deployed in too many prod environments to change this project's name at this point. 😓
