### ISSUE TITLE
Redis steam broker implementation

### ISSUE THREAD

**Issue by cw1427** [faust-streaming/faust#140]
First of all thank you so much for this project which is pretty good.

This is NOT an issue but a request. If it is possible to think about integrate Redis steam broker instead of Kafka. Kafka is really good but too heavy than Redis stream on maintain.  And Redis steam is very light and already used. I don't know if Faust could abstract the broker integration layer to use Redis stream or not.

I'm trying my best to read the source code, but very hard to catch the point for custmizing it. If this is a big problem, effert for implement, then nevermind. Thanks all the same.

**Comment by patkivikram** [comment]
Unfortunately the implementation of faust is tightly coupled with Kafka using aiokafka as its driver. Porting it to use Redis would mean we will have to implement another driver integration. Contributions are welcome!

**Comment by ryou90** [comment]
If you want to use Redis as a broker, then I recommend Celery as an alternative.

**Comment by saranglakare** [comment]
> If you want to use Redis as a broker, then I recommend Celery as an alternative.

Celery does not work with Redis streams IFAIK.
