### ISSUE TITLE
Faust Application is creating internal topics which should not be created

### ISSUE THREAD

**Issue by Prashant-1305** [faust-streaming/faust#149]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
When the application is initialized in a Kafka Cluster Faust is creating an internal topic which is not being used. This is getting created with default settings. 

Tell us what you did to cause something to happen.

## Expected behavior
Internal topic shouldn't be created in Kafka Clusters
Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version 3.8
* Faust version 6.1
* Operating system 
* Kafka version 1.4.2
* RocksDB version (if applicable)

**Comment by patkivikram** [comment]
I believe the problem here is the internal `*__assigner__leader` topic which is created here is not honoring the replication factor set by the app.
