### ISSUE TITLE
It does not scale horizontally the document must be modified

### ISSUE THREAD

**Issue by arezamoosavi** [faust-streaming/faust#154]
The Readme says:
Distributed
Start more instances of your application as needed.

I 've checked it and with the same consumer group and partiotion it does not scale. With more partition it will scale but I wondered with one partition.

**Comment by elrik75** [comment]
I'm new in Faust, but do you have more than 1 Kafka partition? I suppose you need multiple Kafka partitions to be able to scale.
If yes, I guess that Faust developpers will need more information about you issue.

**Comment by bobh66** [comment]
As @elrik75 says you have to have at least one partition for each worker, so if you want to scale horizontally to 10 workers you will need at least 10 partitions.

Also the framework does not scale automatically, that would need to be handled externally depending on your environment.
