### ISSUE TITLE
Suggestion: add other KV store methods

### ISSUE THREAD

**Issue by dbischof90** [faust-streaming/faust#178]
Thanks for picking up this repo from the dead. While we're at it - does it make sense to also add support for other KV stores besides rocksdb? The project itself is alive I think but the python libraries have a hard time.  I don't propose to replace rocksdb - but, from the experience, is it feasible adding other db back ends to faust?

**Comment by wbarnha** [comment]
It's certainly possible. Support for Aerospike was added, but I'm not sure if it's within our project goals at the moment. Our fork for python-rocksdb was recently made portable so I don't think we'll need to look into other alternatives for a while.
