### ISSUE TITLE
table_route decorator doesn't appear to give results as expected

### ISSUE THREAD

**Issue by fonty422** [faust-streaming/faust#187]
I'm trying to get a web view of a table, where I have several workers contributing to the overall table.
The [documentation](http://fauststream.com/en/latest/userguide/tasks.html#http-verbs-get-post-put-delete) seems to suggest that using the @app.table_route decorator reroutes the request to the worker that holds the key, but my requests to a different worker come back with a zero which suggests it doesn't find the key in the table.

If I make the request directly to the worker that is writing that key/value pair to the table, then I get the expected value.

A silly work around would be to write the data to a topic, which then is written to a table which is on a single worker that is used for api GET requests, but it seems like:

1. Too much replication of the exact same data
2. There's no point to workers if the work they do can't be visible outside of the worker.

Please correct me if I'm wrong and a good method is to pipe the incoming data through multiple streams (albeit duplicated) in order to arrive at a single desired result.

## Expected behavior

Expect to make a GET request to the page view address and have returned the current table value for the given key

## Actual behavior

Returns a zero value rather than the true current count value

**Comment by ondrejchmelar** [comment]
We've encountered this issue as well. It works fine in Robinhood's original version.

**Comment by fonty422** [comment]
So it leads to the question, what changed to break this feature?

**Comment by ondrejchmelar** [comment]
I didn't find any change in faust code. `faust-streaming` uses different `aiokafka` library, maybe there's a difference?

Any chance it was fixed by https://github.com/faust-streaming/faust/commit/c1a6b0e216f62fe01f898f7dca7054bb7622161f ?

**Comment by ran-ka** [comment]
This might be a networking issue, can you please check:
- If you are using the default web port (6066) or modify it by running faust --web_port from the CLI?
- If the workers are all in the same subnet? i.e. can they reach each other...
- What do you get by running socket.gethostname() in the worker environment?

The worker will attempt to route the request to the canonical_url URL(f"http://{web_host}:{web_port}"), so make sure it is reachable...

**Comment by fonty422** [comment]
Thanks @ran-ka.
The entire cluster is running in dev on a single machine (zookeeper, kafka, and workers), so they really should all be able to see each other. I'm using both the default 6066 to 60xx incrementing as required.
I'll check the `socket.gethostname()`, but I can't imagine that it will return anything unexpected.

**Comment by ran-ka** [comment]
I see. Just curious, how do you set the individual worker ports, using --web_port from the CLI or using the app configuration? The reason I am asking is that I believe there is a bug in this code (https://github.com/faust-streaming/faust/pull/196).  Anyway, the way I eventually found this bug, is by adding a log at this line, https://github.com/faust-streaming/faust/blob/master/faust/app/router.py#L73, logging routed_url... maybe this will help you to find the issue that you are facing

**Comment by fonty422** [comment]
We do it via the CLI with the `--web-port=XXXX` command. If we don't parse that, then we get the web-port in use error, if we do, then it all works just fine.
