### ISSUE TITLE
AeroSpike state storage doesn't recover from stored data, replays changelogs instead

### ISSUE THREAD

**Issue by xaralis** [faust-streaming/faust#207]
## Steps to reproduce

Configure faust to use `aerospike://` as the table storage engine. Then, make sure some tables actually use that (need to provide AeroSpike instance as the target).

App config:

```python
app = faust.App(
    ...
    store='aerospike://',
    ...
)
```

Table config:

```python
aerospike_enabled_table = app.Table(
    'mytable',
    default=dict,
    key_type=bytes,
    options={
        'client': {
            'hosts': [('127.0.0.1', 3000)],
        },
    },
)
```

## Expected behavior

When faust boots up, the data recovery uses AeroSpike instance rather than falling back to replaying Kafka changelog topics.

## Actual behavior

Faust ignores what's stored in AeroSpike and replays changelogs. The behavior is basically identical to `memory://` storage engine which makes me wonder what is the actual purpose of AeroSpike storage engine.

I suspect, the goal with AeroSpike was something else than data recovery. I'm guessing by looking at the code:

https://github.com/faust-streaming/faust/blob/7600f45e2f1beb1e1c1d431c8660c821bd8a7db8/faust/stores/aerospike.py#L232-L237

It seems that no matter what was stored, faust will always think the storage is empty. Is this intentional? Is the AeroSpike engine ready for real use? Shall we create an PR with recovery support?

Thanks!

# Versions

* Python version - 3.9.7
* Faust version - 0.6.10
* Operating system - macOS/Linux - applies to both
* Kafka version - 3.0.0
* AeroSpike version - ce-5.7.0.7

**Comment by patkivikram** [comment]
CE is fine
