### ISSUE TITLE
Recovery hangs in Fetcher

### ISSUE THREAD

**Issue by patkivikram** [faust-streaming/faust#21]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
We have noticed that on a restart the recovery hangs with the only message from the fetcher and then it just hangs indefinitely

## Expected behavior

Recovery should not hang
## Actual behavior

Hangs with the following log message
`[^----Fetcher]: Starting...`
## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version 3.8
* Faust version 1.11.0a1
* Operating system centos
* Kafka version 2.4
* RocksDB version (if applicable) 6.7

**Comment by marcosschroh** [comment]
The version for `faust-streaming` is `0.1.0`

**Comment by austinnichols101** [comment]
@patkivikram - I was able to work around a similar timing issue with the following code.  Interested to see if it has any impact on your issue.  

```
class FaustApp(faust.App):

    # MDYER: Add a delay to work around the "Fetch offset" hang issue
    def on_rebalance_return(self, *args, **kwargs):
        interval = 5
        logger.info(f'on_rebalance_return - {interval}')
        time.sleep(interval)
        super().on_rebalance_return(*args, **kwargs)
```

**Comment by marcosschroh** [comment]
@austinnichols101 your solution does not work for me. I tried and also I have increased the interval. I think it can not be solved redefining `on_rebalance_return`

**Comment by austinnichols101** [comment]
Yup - I spoke with @patkivikram and it appears to be a different issue...

**Comment by patkivikram** [comment]
This was merged to master today
