### ISSUE TITLE
Update dependency `click` >= 8

### ISSUE THREAD

**Issue by qbzenker** [faust-streaming/faust#230]
Hi,

Right now there is a dependency for this project `click>=6.7,<8.0`, are there plans to upgrade to allow click 8+? 

I'd be happy to contribute to the dependency upgrade if needed - wanted to see if it's on the near-term roadmap as we have a dependency on click 8+ and are also heavy users of this project.

Thanks, really appreciate all of the work that's gone into maintaining this faust fork!!

**Comment by patkivikram** [comment]
I don't think anyone is working on it. Happy to review your PR with the required changes

**Comment by qbzenker** [comment]
Closing because the package bump PR was merged.
