### ISSUE TITLE
App shutdown hook?

### ISSUE THREAD

**Issue by jjwwiodyne** [faust-streaming/faust#254]
During Faust shutdown I need to run clean up on a number of objects/connections before the event loop is terminated. Is there a shutdown hook I can register with? Looking through the docs and code I had trouble finding the right way to do this. 

For example [FastAPI](https://github.com/tiangolo/fastapi) has a `shutdown` event you can register with:
```python
    @new_app.on_event("shutdown")
    async def shutdown_event():
        await do_teardown_things()
```

Thank you in advance.

**Comment by patkivikram** [comment]
you could extend https://mode.readthedocs.io/en/latest/reference/mode.services.html#mode.services.Service.stop by creating a wrapper around Faust Service?

**Comment by dabdada** [comment]
There is a on_before_shutdown signal you can connect to. Not sure if this is too early for your usecase though https://github.com/faust-streaming/faust/blob/master/faust/app/base.py#L539

Use like:

    @app.on_before_shutdown.connect
    def on_shutdown(app, **kwargs):
         print("shutdown")
