### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by jacksmith15** [faust-streaming/faust#267]
## Feature request: Python 3.10 support

It looks like `mode-streaming` 0.2.0 adds support for Python 3.10. It would be great if Python 3.10 support could be rolled out to `faust-streaming` too.

From an initial run of tests using `mode-streaming==0.2.0` and Python 3.10, I see:

> 132 failed, 1719 passed, 100 skipped, 6111 warnings, 145 errors in 108.00s (0:01:47)

The vast majority of the errors appear to be due to passing the `loop` parameter to asyncio primitives.

**Comment by hellocoldworld** [comment]
See #205

**Comment by austinnichols101** [comment]
See #205

**Comment by VikalpRusia** [comment]
please release a wheel build so that it can be installed using pip

**Comment by ExpLog** [comment]
I second that!

It would be really cool if the maintainers could release a new version that includes 3.10 support that has already been merged to master 😄

**Comment by austinnichols101** [comment]
@patkivikram @taybin ^^

**Comment by AntonOfTheWoods** [comment]
@patkivikram @taybin is the general policy moving forward going to be that we should simply point to a github commit as our package repo, or is the idea to keep doing releases?

**Comment by taybin** [comment]
@AntonOfTheWoods unfortunately, I can no longer help maintain this project.  It would be nice to see a new release with the python-3.10 work, but I am unable to either release it or help with issues surrounding the python-3.10 work.

**Comment by wbarnha** [comment]
The project supports 3.10 and we're about to merge in a change that automatically builds 3.10 wheels on release. I'll mark this as closed.
