### ISSUE TITLE
Question: Regarding the release process

### ISSUE THREAD

**Issue by lindycoder** [faust-streaming/faust#275]
Hello,

I noticed a faust-streaming 0.8.3 appeared on pypi (https://pypi.org/project/faust-streaming/0.8.3/), but I don't see a tag or release.

Luckily this particular release doesn’t appear to be malicious, however it does raise some concerns in light of recent supply chain attacks as the [documented release procedure](https://github.com/faust-streaming/faust/blob/master/docs/contributing.rst#release-procedure) does not appear to have been followed.

If possible, could you shed some light ?

**Comment by patkivikram** [comment]
it is deleted in pypi and 0.8.4 was released. 0.8.3 was deployed from a dev branch while testing a feature
