### ISSUE TITLE
Question: base version of robinhood/faust and confluent kafka driver

### ISSUE THREAD

**Issue by joonjeong** [faust-streaming/faust#280]
What is the base version of robinhood/faust?

It looks that the last commit was 01b4c0a by @ask, and I just guess 1.10.4 is the base of this repo and re-versioned.

and, there's no plan to support confluent kafka driver? aiokafka support is the only plan?
There is confluent driver on robinhood/faust but not in this fork.

**Comment by danriedl** [comment]
Hi @joonjeong,
The driver had been removed by @[marcosschroh](https://github.com/marcosschroh) in [PR-12](https://github.com/faust-streaming/faust/pull/12).
