### ISSUE TITLE
Current project priorities

### ISSUE THREAD

**Issue by rodrigorivera** [faust-streaming/faust#302]
Hi everyone,

I am interested in contributing to the project, but I lack an overview of the priorities and current needs. 

I am primarily interested in working on the documentation and on functionality on top of Faust, such as including algorithms like heavy hitters or count min sketch.

May someone share a list of priorities for Faust Streaming, please?

**Comment by AntonOfTheWoods** [comment]
Alas, it looks like `faust-streaming` might be going the way of `faust`, into that good night.

**Comment by AntonOfTheWoods** [comment]
@patkivikram but no one to release or answer any queries about when/if a release might happen?

**Comment by AntonOfTheWoods** [comment]
To be honest I am actually investigating migrating off faust due to the lack of project momentum. I absolutely love the idea of it but have far, far too many other things on the go to try and invest the time to move it forward myself.

**Comment by tritas** [comment]
Then you're just creating noise..

**Comment by AntonOfTheWoods** [comment]
@tritas well the silence is pretty deafening and I'm not seeing any activity from you either...

**Comment by hdhillan** [comment]
> To be honest I am actually investigating migrating off faust due to the lack of project momentum. I absolutely love the idea of it but have far, far too many other things on the go to try and invest the time to move it forward myself.

@AntonOfTheWoods What Faust alternatives are you considering?

**Comment by AntonOfTheWoods** [comment]
@hdhillan my hope is that they won't spend another 5 years before finally supporting `kafka` in `celery` for tasks (in theory it could be implemented very easily now), and for stats (I was using `rocksdb`) I have already migrated to a plain `postgres` db.

**Comment by wbarnha** [comment]
The current goals of this project is to:

1. Address ongoing bugs
2. Improve documentation

There isn't much activity going on in terms of extending functionality. If you would like to add an improvement, please feel free to file a PR and I'll be happy to review it. 🙂
