### ISSUE TITLE
Questions about faust and prometheus

### ISSUE THREAD

**Issue by lchunleo** [faust-streaming/faust#320]
Hi

 am new to faust stream. i wish to understand better how does faust stream data can be captured by prometheus. Currently my understanding is that the faust stream data can be written into the rocksdb but am clueless how it will flow from there on wards. Can someone advise? thank you

**Comment by hdhillan** [comment]
I'm also new here, but my understanding of the Prometheus support is that Faust will expose a metrics endpoint ('/metrics') for Prometheus to scrape to obtain metrics regarding the operation of Faust. You can refer to the source code here https://github.com/faust-streaming/faust/blob/master/faust/sensors/prometheus.py#L42

I have not tried it, but it looks like you could pass your own instance of the `CollectorRegistry` (see https://github.com/prometheus/client_python) to `setup_prometheus_sensors` which would allow you to register your own, custom Counters, Gauges etc... which you could then increment in your agents.

**Comment by lchunleo** [comment]
> I'm also new here, but my understanding of the Prometheus support is that Faust will expose a metrics endpoint (`/metrics`) for Prometheus to scrape to obtain metrics regarding the operation of Faust. You can refer to the source code here https://github.com/faust-streaming/faust/blob/master/faust/sensors/prometheus.py#L42
> 
> I have not tried it, but it looks like you could pass your own instance of the `CollectorRegistry` (see https://github.com/prometheus/client_python) to `setup_prometheus_sensors` which would allow you to register your own, custom Counters, Gauges etc... which you could then increment in your agents.

Thank you , let me check it out on your link. :)
