### ISSUE TITLE
Faust hangs on publish_message unpredictabilly

### ISSUE THREAD

**Issue by dabdada** [faust-streaming/faust#322]
## Steps to reproduce

We are using faust-streming within our fastAPI application and start faust on fastAPI event startup with:

    asyncio.create_task(faust_app.start())

Unfortunatelly after some time (as of now non deterministic so I can not provide a reproducable example sorry) we are not able to consume or produce messages. However in the producer we do see the debug log publish_message called with key=b'xxx' and value=b'{"some":"json"}', but the message is not sent to Kafka. Nevertheless we do see mode.timers 

We run only one broker, one faust application, on a topic with one partition. And suspect some rebalincing issues.

Are there any insights on this yet?

## Expected behavior

Faust should not hang.

## Actual behavior

Faust hangs without any error

## Full traceback

There is none.

# Versions

* Python version: 3.9.x
* Faust version: 0.8.4 and 0.8.5 (maybe also earlier, maybe config issue on our side)
* Operating system: Debian
* Kafka version: 3.1.0
* RocksDB version (if applicable): 6.29.3 (shouldn't be an issue here though)

Any help and hints are highly appreciated, thank you.

**Comment by dabdada** [comment]
It might be due to running on K8s and rebalancing on application restart. Is there a reason for not allowing to set consumer_group_instance_id (https://github.com/faust-streaming/faust/blob/84302f57e8a232ca81c2689805b9ee8b63bcc202/faust/transport/drivers/aiokafka.py#L520)?

**Comment by aoberegg** [comment]
There is an open PR in aiokafka that supports this --> https://github.com/aio-libs/aiokafka/pull/827/files

**Comment by dabdada** [comment]
Sorry as already stated this has been an issue on our side and how we start faust alongside with fastAPI.
