### ISSUE TITLE
https://fauststream.com not updating from repo

### ISSUE THREAD

**Issue by russellpierce** [faust-streaming/faust#336]
I'm not sure if this will be welcomed as an issue - but I'm going to call this ~ 'small contributions' and ask for grace.

## Steps to reproduce

I navigated to [the fauststream documentation website and clicked the 'Contributing' link](https://fauststream.com/en/latest/contributing.html).  

## Expected behavior

I expect the documentation to link back to the faust-streaming repository.  But, all documentation issue links back to the robinhood repo (both the text and href).

## Actual behavior

![The issue tracker points to the robinhood/faust repo](https://cdn.zappy.app/294135b4b61df0304083c4e4f73a3e29.png)

## Additional Info

* The .rst in this repo are correct.
* The python-package workflow hasn't completed on the `master` branch successfully for [~22 days as of this writing](https://github.com/faust-streaming/faust/actions/workflows/python-package.yml?query=branch%3Amaster). 
* That workflow not completing can't account for the discrepancy as the PR to correct these issues https://github.com/faust-streaming/faust/pull/290 was merged in March

**Comment by wbarnha** [comment]
Hopefully by the next release, we'll have this issue worked out. We've added some features in `v0.8.6` and `v0.8.7` that users wouldn't know how to use unless docs are generated.
