### ISSUE TITLE
Fix that released all fetch waiters introduced error messages for idle Faust worker

### ISSUE THREAD

**Issue by forsberg** [faust-streaming/faust#37]
## Checklist

- [X] I have included information about relevant versions
- [X] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Run a faust worker that waits for messages on a topic with no or very little traffic.

## Expected behavior

Worker should sit and do nothing.

## Actual behavior

I get ERROR level messages as follows:

```pytb
[2020-11-17 16:19:03,695] [708969] [ERROR] Exception in callback Fetcher._create_fetch_waiter.<locals>.<lambda>(<Future cancelled>) at /home/forsberg/.virtualenvs/ferrostream/lib/python3.8/site-packages/aiokafka/consumer/fetcher.py:446
handle: <Handle Fetcher._create_fetch_waiter.<locals>.<lambda>(<Future cancelled>) at /home/forsberg/.virtualenvs/ferrostream/lib/python3.8/site-packages/aiokafka/consumer/fetcher.py:446> 
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/forsberg/.virtualenvs/ferrostream/lib/python3.8/site-packages/aiokafka/consumer/fetcher.py", line 446, in <lambda>
    lambda f, waiters=self._fetch_waiters: waiters.remove(f))
KeyError: <Future cancelled>
```

Problem goes away if I revert 361b09dde7de3c7314d7cac7447e029a8e54c97b (releasing all fetch waiters).

Problem also seems to appear during rebalance for busy workers, i.e workers where the input topic is busy.

# Versions

* Python version 3.8.5
* Faust version faust-streaming 18230a729a717a05aad2a2df58dfe494917de2ab
* Operating system Linux
* Kafka version 2.5.0
* RocksDB version (if applicable) N/A

**Comment by patkivikram** [comment]
This is fixed in release 0.3.0 with PR https://github.com/faust-streaming/faust/pull/45
