### ISSUE TITLE
Regression due to fix for #313

### ISSUE THREAD

**Issue by patkivikram** [faust-streaming/faust#378]
## Checklist

- [ x] I have included information about relevant versions
- [ x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

When a compacted topic with gaps is processed by an agent, the consumer never commits any offsets

## Expected behavior

The consumer should identify gaps in the topic and acknowledge messages

## Actual behavior

The consumer stop committing offets. This is likely due to https://github.com/faust-streaming/faust/pull/313

# Versions

* Python version 3.8
* Faust version 0.8.6
* Operating system Centos

**Comment by wbarnha** [comment]
I'm surprised our unit tests didn't pick this up. It'd be nice to add another unit test with this to make sure the new change works as intended.
