### ISSUE TITLE
hacktoberfest 2022

### ISSUE THREAD

**Issue by joonjeong** [faust-streaming/faust#395]
Hi, is it possible to link with hactoberfest 2022?

* Hacktoberfest 2022 -PR/MR Details: https://hacktoberfest.com/participation/#pr-mr-details

**Comment by wbarnha** [comment]
I'd be happy to have this project involved with Hacktoberfest. Let me read the fine print and see if there's anything needed from us.

**Comment by wbarnha** [comment]
Done, thanks for the suggestion. If I knew about hacktoberfest, I would've tagged this project much sooner. I have labelled #392 as `hacktoberfest-accepted` for you. Please feel free to make another PR if you are looking to do more. One thing I can think of immediately is fixing the formatting on https://faust-streaming.github.io/faust/reference/faust.html#faust.Stream.take_events.
