### ISSUE TITLE
Authentication for SCRAM_SHA_512

### ISSUE THREAD

**Issue by smeana** [faust-streaming/faust#397]
How do you specify mechanism=SASLMechanism.SCRAM_SHA_512? 
Using version 1.10.4 
I can only see PLAIN and GSSAPI

```
class SASLMechanism(Enum):
    PLAIN = 'PLAIN'
    GSSAPI = 'GSSAPI'
```
 
 How can I make this work for SASL_SSL with SCRAM_SHA_512?
```
 ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH, cafile='../certs.pem')

 app = faust.App('cod_error_count_sap',
                autodiscover=True,
                broker=[
                    URL("kafka://....:9093"),
                    URL("kafka://.....:9093"),
                    URL("kafka://......:9093"),
                    URL("kafka://.....:9093"),
                    URL("kafka://.....:9093"),
                ],
                broker_credentials=faust.SASLCredentials(username='......', password='......',
                                                         ssl_context=ssl_context, mechanism=SASLMechanism.SCRAM_SHA_512),
                store='rocksdb://'
                ) 
```

**Comment by wbarnha** [comment]
> Using version 1.10.4

I think you installed the Robinhood version of Faust by accident. Try uninstalling it then installing via `pip3 install faust-streaming`.

**Comment by wbarnha** [comment]
Definitely the wrong version of Faust installed, The original `faust` project only has those options as indicated by https://faust.readthedocs.io/en/latest/reference/faust.types.auth.html?highlight=auth#module-faust.types.auth. Our fork has https://faust-streaming.github.io/faust/reference/faust.types.auth.html#faust.types.auth.SASLMechanism.SCRAM_SHA_512. Just fix the installation and you should be good.
