### ISSUE TITLE
Update dodumentation

### ISSUE THREAD

**Issue by marcosschroh** [faust-streaming/faust#4]
I would like to update the documentation and make it more clear. I would like to use `markdown` and publish the documentation in `github` pages. For example: https://marcosschroh.github.io/dataclasses-avroschema/

**Comment by tarbaig** [comment]
There are a few bugs in the documentation. What would  be the correct place to fix those as a contribution to this issue?

**Comment by marcosschroh** [comment]
I am working in the new doc, I think at the end of this week will we available. After that you can send your PR

**Comment by mozcelebi** [comment]
any update on the documentation?

**Comment by tarbaig** [comment]
How is the status of the new doc? We keep finding hidden features in the code that could benefit from being public knowledge.
Currently they just go into our internal wiki.

**Comment by marcosschroh** [comment]
I was working on this one in order to use github pages. Unfortunately, for personal issues I stopped. I can push the branch that I was working and someone can continue the work.

**Comment by tarbaig** [comment]
I can't promise I'll have time to do it, but if you push ( and maybe add a few remarks about missing work) I'll attempt to fit it into my schedule.
