### ISSUE TITLE
topic.send without running loop

### ISSUE THREAD

**Issue by joonjeong** [faust-streaming/faust#411]
hi, I'd like to make a command line tool to send message to topic.

I made async func and just await like this, but no message is sent.

```python
def handle():
    async def handle_async():
        await topic1.send(value=ActionRequest(desired="FIRING"))

    asyncio.run(handle_async())
```

I guess it's related with faust's lifecycle but I have no idea with sending message with faust api.

any idea with tooling?

**Comment by thomas-chauvet** [comment]
Hi,

I think you should look at the CLI doc [here](https://faust-streaming.github.io/faust/userguide/tasks.html#custom-cli-commands). 

It will answer your need.

Basically, you will need to add the decorator `@app.command()` at the top of your function.

If your need is **only** to create a CLI to interact with Kafka topics, you should check [kafka-rest](https://github.com/confluentinc/kafka-rest).

If you want a custom CLI, you should use [typer](https://typer.tiangolo.com/) or [click](https://click.palletsprojects.com/en/8.1.x/) on which faust is based on for the CLI part. To interact with kafka you can use [aiokafka](https://aiokafka.readthedocs.io/en/stable/).

**Comment by wbarnha** [comment]
@thomas-chauvet is correct, thank you very much for providing assistance! I will mark this as closed.
