### ISSUE TITLE
Slack Invite Link is no longer active

### ISSUE THREAD

**Issue by ez-ish** [faust-streaming/faust#424]
Hey is this slack still active? 

## Steps to reproduce

clicked the invite link here
- https://faust-streaming.github.io/faust/introduction.html#getting-help

**Comment by wbarnha** [comment]
The Slack is still active! I'll get a new invite link up shortly.

**Comment by wbarnha** [comment]
You can use https://join.slack.com/t/fauststream/shared_invite/zt-1lwkumad3-4FQvrp8MdAbXcFjk0xf8fQ for the next thirty days. I'll look into getting a permanent invite working.

**Comment by wbarnha** [comment]
https://join.slack.com/t/fauststream/shared_invite/zt-1lwkumad3-4FQvrp8MdAbXcFjk0xf8fQ is now a permanent invite link, I'll go ahead and update the docs. Thanks for letting us know!
