### ISSUE TITLE
Do you plan to also fork mode, because it seems abandonned.

### ISSUE THREAD

**Issue by max-k** [faust-streaming/faust#43]
Hi,

Thank you for your work.

Do you plan to also fork mode ?

It is another project formerly maintained by a robinhood employee and today it looks abandoned.

It is an important dependency of Faust so it could be valuable to keep it updated in parallel of your Faust fork.

If there is anything I can do help you in this process, just ask.

Thank you very much.

**Comment by patkivikram** [comment]
Are there any pending feature bugs that need to be addressed?

**Comment by max-k** [comment]
Hi,

Yes, at least the PR I made on the project to fix a bug regarding custom event loop usage.

[Pass loop attribute to asyncio.ensure_future #66](https://github.com/ask/mode/pull/66)

**Comment by patkivikram** [comment]
We can make a fork of it. Should I add you as a maintainer @max-k ? That way you can create a fork of it and merge it

**Comment by max-k** [comment]
I'm not sure I have the skills needed to maintain the whole thing but I can try to help, at least.

**Comment by max-k** [comment]
Hi,
I made the fork and re-create my MR on it.
I'm currently updating the README.
Do you have a suggestion for the name of the python artifact ? (mode-fork ? mode-streaming ? faust-streaming-mode ?)

**Comment by patkivikram** [comment]
`mode-streaming`? I will leave it to you :)

**Comment by max-k** [comment]
mode-streaming sounds not so bad. Let's go for it. Thank you very much.

**Comment by max-k** [comment]
1.

**Comment by lqhuang** [comment]
@max-k Hey, thanks for your effort. I have had a pull request for two weeks ago faust-streaming/mode#6, but it's still in pending state. Could you take a look?  Do you still pay time to keep maintaining `mode`. I volunteer to be a maintainer of this fork. A lot of my applications are depending `mode` package. I'm like to add more features to `mode`. Of course, the compatibility to `faust-streaming` is first priority. @patkivikram

**Comment by max-k** [comment]
Hi @lqhuang , Thank you for your contribution. I'll take a look at it as soon as possible.
