### ISSUE TITLE
Is there a way to log processed events?

### ISSUE THREAD

**Issue by bradydean** [faust-streaming/faust#454]
I've been looking around I don't see an option for it, or any indication it exists, but I'm looking for a way to log each event as they are processed. Just simple stuff like the date, topic, etc. It seems I would have to write this code by hand in each agent at the moment.

**Comment by wbarnha** [comment]
Faust has a log of logging functionality built into it, as does `mode-streaming` since it does some magic to the logging handlers. You may want to check out https://faust-streaming.github.io/faust/userguide/sensors.html.

**Comment by bradydean** [comment]
@wbarnha Do you have any docs I could reference on the mode logging magic? I'm trying to get a logger/handler for stdout but everything goes to stderr.

```
    logging_config={
        "version": 1,
        "merge": True,
        "loggers": {
            "my.package": {
                "level": "INFO",
                "handlers": ["accesslog"]
            },
        },
        "handlers": {
            "accesslog": {
                "class": "logging.StreamHandler",
                "level": "INFO",
                "stream": sys.stdout,
            }
        }
    }
```
