### ISSUE TITLE
It would be better if this was actually clone of https://github.com/PyYoshi/cChardet

### ISSUE THREAD

**Issue by mcepl** [faust-streaming/faust#457]
Then it would be

1. obvious this is a fork
2. it could be possible to see how far is that upstream from here.

I guess you will have to ask for the support. Hmm, there is https://support.github.com/request/fork perhaps it could help.

**Comment by wbarnha** [comment]
I created a fork of PyYoshi's project because the cchardet project stopped being maintained. I tried contacting the maintainer and I never got a response. Ultimately, I was left with no choice but to fork and maintain my own fork.

**Comment by wbarnha** [comment]
I'm honored to have the maintainer of `m2crypto` paying attention to this project by the way 😄 

Did you mean indicate this is a fork of https://github.com/robinhood/faust? If so, I'll reopen and try to address it.

**Comment by mcepl** [comment]
I am sorry, this is just a PEBKAC, I confused this repo with https://github.com/faust-streaming/cChardet and that’s properly marked as a fork. Sorry.

Concerning M2Crypto, I am nothing but an useless idiot, who cannot force himself to complete even one milestone now. So, calling me a maintainer of that is more embarrassing than anything.
