### ISSUE TITLE
Question: Is there any way to prevent agents from starting until a task is complete?

### ISSUE THREAD

**Issue by fgimian** [faust-streaming/faust#46]
Hey there guys, I'm sorry I didn't fill in the template as this is more of a question.

Our application must read some data from a database before starting to process streams, as the loaded data is correlated with certain fields of a  message that arrives.

At present, I don't seem to see an elegant way of doing this other than having a global bool and making the agent sleep until this bool changes to indicate loading has completed.

Is there any other way to accomplish this?

Huge thanks
Fotis

**Comment by jkgenser** [comment]
Can you use on_worker_init signal? From what I can tell this should run before the worker starts processing a stream. Haven't tested it though.

https://faust.readthedocs.io/en/latest/userguide/application.html#app-on-worker-init

**Comment by fgimian** [comment]
> Can you use on_worker_init signal? From what I can tell this should run before the worker starts processing a stream. Haven't tested it though.
> 
> https://faust.readthedocs.io/en/latest/userguide/application.html#app-on-worker-init

Thanks heaps, I'll give it a try and let you know how it goes 😄

**Comment by fgimian** [comment]
Since this question is answered now, I'll close the ticket, thanks!
