### ISSUE TITLE
Please make aiohttp optional

### ISSUE THREAD

**Issue by SiDChik** [faust-streaming/faust#484]
May be possible make aiohttp optional? I dont have any views in faust app, so why i need install aiohttp?

**Comment by patkivikram** [comment]
Have you tried using https://faust.readthedocs.io/en/latest/userguide/settings.html?highlight=web_server#std:setting-web_enabled

**Comment by wbarnha** [comment]
I have contemplated this as well. I've never personally used the web browser for anything, and we normally use the `--without-web` setting. My only concern is interfering with users who already have their ecosystems configured to assume `web_enabled=True`.

Is there a particular requirement as to why `aiohttp` needs to be an optional requirement? The wheels are 1 MB, which isn't too bad, compared to other dependencies.

**Comment by SiDChik** [comment]
The project uses aionttp of a certain version. Then i add faust i have get dependency conflict.

**Comment by wbarnha** [comment]
What version of `aiohttp` do you need to use? Looks like I bumped the requirement from 3.5.2 to 3.8.3 in https://github.com/faust-streaming/faust/commit/cf397bc9a2398230f23cb04aba42e9e06132c13c

**Comment by wbarnha** [comment]
Looks like 3.8.2 was yanked: https://pypi.org/project/aiohttp/3.8.2/

Regardless, I should've left notes explaining why I updated to 3.8.3. Let me retest things and see if I can make a more lenient requirement.

**Comment by mozTheFuzz** [comment]
Hi, I am trying to use the app with 
web_enabled = False 

But the it does not work as expected

but when I run the following, aiohttp is turned off as expected.

faust xxx.py worker -l info --without-web

**Comment by wbarnha** [comment]
> Hi, I am trying to use the app with web_enabled = False
> 
> But the it does not work as expected
> 
> but when I run the following, aiohttp is turned off as expected.
> 
> faust xxx.py worker -l info --without-web

What version of Faust are you using? Could you provide a traceback?

By the way, I think this belongs in a separate issue.
