### ISSUE TITLE
Add support for aerospike > 8.0

### ISSUE THREAD

**Issue by patkivikram** [faust-streaming/faust#496]
## Checklist
Current faust implementation does not support aersopike > 8.0
- [x ] I have included information about relevant versions
- [ x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Tell us what you did to cause something to happen.

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version
* Faust version 0.10.11
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by wbarnha** [comment]
I believe merging #498 sufficiently allows us to close this now.
