### ISSUE TITLE
newer version of open tracing

### ISSUE THREAD

**Issue by tarbaig** [faust-streaming/faust#50]
## Checklist

- [ X ] I have included information about relevant versions
- [ X ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Install faust together with a current version of jaeger-client (which requires opentracing>=2.1)

## Expected behavior

No version conflict should arise

## Actual behavior

faust claims to be unable to work with opentracing>=2.0.0

## Full traceback

```bash
ERROR: jaeger-client 4.3.0 has requirement opentracing<3.0,>=2.1, but you'll have opentracing 1.3.0 which is incompatible.
```

# Versions

* Python version
3.7
* Faust version
faust-streaming-0.3.0
* Operating system
linux

According to [this issue](https://github.com/robinhood/faust/issues/528) in the original project just bumping the version number [here](https://github.com/faust-streaming/faust/blob/be1e6dbe2507fd068a40391dcd2ddd436372661e/requirements/requirements.txt#L7) should be enough to enable opentracing>2.0.0.

The reason it was not upgraded in the original project was a possible incompatibility in robinhoods closed source internal tracing framework.

I tried it locally and all tests work.

**Comment by patkivikram** [comment]
Sounds good - we use it for datadog with opentracing>=2.0.0. Can you create a PR?
