### ISSUE TITLE
Table TTL 

### ISSUE THREAD

**Issue by mooneym17** [faust-streaming/faust#515]
Hi All,

This is more of a question than an issue  - not sure if you have a community channel instead?

i see someone posted on the original faust repo, asking if and how we can expire table entries using TTL in 2018 - https://github.com/robinhood/faust/issues/230 . Has this feature been implemented?  This would be handy to prevent table bloat over time, when not using windowed tables.

**Comment by wbarnha** [comment]
Can't believe I didn't stumble upon this issue sooner. It's a great idea that could benefit many. Looks like `rocksdict` has support in https://congyuwang.github.io/RocksDict/rocksdict.html#AccessType and if I use `python-rocksdb`, I need to set `wal_ttl_seconds`.
