### ISSUE TITLE
How to use generic records?

### ISSUE THREAD

**Issue by SergiusAC** [faust-streaming/faust#526]
I'd like to use generic classes as records, like this:

```
T = TypeVar("T")

class GeneralRecord(faust.Record, Generic[T], metaclass=ABCMeta):
    record_type: str
    record_data: T

class ProductRecord(faust.Record, metaclass=ABCMeta):
    product_name: str

---------

some_topic = app.topic("some_topic", value_type=GeneralRecord[ProductRecord])

@app.agent(some_topic)
async def process_product(stream):
  async for record in stream:
    process(record.record_data.product_name)

```

But when I use this kind of records, I get the next error: `AttributeError: 'dict' object has no attribute 'product_name'`

Does Faust support generic records or I do something wrong?

## Checklist

- [X] I have included information about relevant versions
- [X] I have verified that the issue persists when using the `master` branch of Faust.

## Versions

* Python version 3.11
* Faust version 0.10.13
* Operating system Windows 10
* Kafka version 6.2.0
* RocksDB version (if applicable)

**Comment by wbarnha** [comment]
Faust is able to export records to generic models as defined in https://github.com/faust-streaming/faust/blob/master/faust/models/record.py#L586-L596. I think the GeneralRecord is getting converted to a dict earlier than it should be, hence why you're encountering the issue you're seeing here.

On another note, you may be in interested in https://marcosschroh.github.io/dataclasses-avroschema/faust_records/.
