### ISSUE TITLE
Faust Scaling Approach

### ISSUE THREAD

**Issue by jainal09** [faust-streaming/faust#535]
## Checklist

- [-] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I am trying to get a good head about faust and its work. So, far I am confused about partition assignment.
I had gone through this docs: https://faust-streaming.github.io/faust/developerguide/partition_assignor.html
So, the thing I need to validate is the approach for scaling the cluster. Let say I have a kafka cluster and a topic with 3 partitions and if I scale it up and add more brokers the partition count increases, in traditional kafka consumers adding more consumers at least no. partitions == no. of partitions is okay

The complexity is there is also faust change log that manages the partition count and it should be equivalent to the partition count of topic or else faust workers sends an error

## Expected behavior

I want to know the approach.

## Actual behavior

Generally a way to scale up the kafka cluster

## Full traceback

# Versions

* Python version: Python 3.10.6
* Faust version: 0.10.14
* Operating system: Ubuntu 22
* Kafka version: 3.4
* RocksDB version (if applicable)

**Comment by wbarnha** [comment]
There isn't a straightforward approach in Faust for scaling topic partitions dynamically on tables for existing topics, and there isn't functionality defined for this in Faust yet.

Suggested reading as to why scaling partitions during runtime is dangerous: 
https://stackoverflow.com/questions/54650298/why-does-kafka-streams-threads-die-when-the-source-topic-partitions-changes-ca
https://stackoverflow.com/questions/62367495/impact-of-adding-partitions-to-an-existing-kafka-topic-on-producer-consumer-beha

The gist is that data needs to be redistributed from the old partitions onto new partitions and other tasks need to take place, which is beyond the scope of Faust.
