### ISSUE TITLE
(docs) Autodetect for schemas

### ISSUE THREAD

**Issue by redb0** [faust-streaming/faust#560]
Hi everyone!

I recently started using this library

In documentation ([link](https://faust-streaming.github.io/faust/userguide/models.html#schemas)) in example for class `Autodetect`  variable `value_type` is not defined before this line

```python
def loads_value(self, app, message, *, loads=None, serializer=None):
    if loads is None:
        loads = app.serializers.loads_value
    # try to get key_type and serializer from Kafka headers
    headers = dict(message.headers)
    value_type_name = headers.get('ValueType')
    serializer = serializer or headers.get('ValueSerializer')
    if value_type_name:
        value_type = registry[value_type]   # <-- value_type is not defined
        return loads(value_type, message.key, serializer=serializer)  # <-- maybe message.value?
    else:
        return super().loads_value(app, message, loads=loads, serializer=serializer)
```

Maybe it was meant `value_type_name`?

Should I pass `message.key` in the last line? Maybe you meant `message.value`?

And also the comment is a victim of copy-paste: `try to get key_type and serializer from Kafka headers` -> `try to get value_type and serializer from Kafka headers`

**Comment by IbrahimBagalwa** [comment]
Hello @redb0, should the `value_type` variable be replaced with `value_type_name`, `message.key` with `message.value`, and the comment `# try to get key_type and serializer from Kafka headers` with `# try to get value_type and serializer from Kafka headers` in this code snippet?

**Comment by IbrahimBagalwa** [comment]
@redb0, If that's the case, I would like to work on it.

**Comment by redb0** [comment]
@IbrahimBagalwa, yes, you wrote everything correctly

I don't mind if you do it

**Comment by IbrahimBagalwa** [comment]
Thanks @redb0
