### ISSUE TITLE
Faust release version not being updated on GitHub

### ISSUE THREAD

**Issue by austinnichols101** [faust-streaming/faust#58]
## Checklist

- [*] I have included information about relevant versions
- [N/A] I have verified that the issue persists when using the `master` branch of Faust.

Currently GitHub shows v0.2.1 as the latest release as shown in the attached screenshot.

![image](https://user-images.githubusercontent.com/6962379/101785071-52175e00-3aca-11eb-970f-e6f5c011e6cb.png)

**Comment by max-k** [comment]
@patkivikram I tried to create new releases but it seems you didn't gave me a sufficient access level to do that.
