### ISSUE TITLE
ModuleNotFoundError: No module named 'mode.utils.typing'

### ISSUE THREAD

**Issue by klajdicaushi** [faust-streaming/faust#617]
In several projects in which we are using faust-streaming, the following error came up today. 
No change was done in the configurations of faust or kafka. 

## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Try to start faust through the cli, with the command: 
```shell
python -m faust -A conf.kafka_consumer:app worker -l info
```

## Full traceback

```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/faust/__main__.py", line 4, in <module>
    from faust.cli.faust import cli
  File "/usr/local/lib/python3.11/site-packages/faust/cli/__init__.py", line 3, in <module>
    from .base import AppCommand, Command, argument, call_command, option
  File "/usr/local/lib/python3.11/site-packages/faust/cli/base.py", line 39, in <module>
    from mode.utils.typing import NoReturn
ModuleNotFoundError: No module named 'mode.utils.typing'
```

# Versions

* Python version - 3.10, 3.11
* Faust version - 0.10.14, 0.10.24
* Operating system - Ubuntu

**Comment by klajdicaushi** [comment]
It seems related to the recent deployment of [mode-streaming](https://pypi.org/project/mode-streaming/0.3.6/)

**Comment by wbarnha** [comment]
Correct. I'll get this patched ASAP. Sorry about that!

**Comment by wbarnha** [comment]
Going to yank `mode-streaming==0.3.6` and release a patch in `0.4.0` shortly. Sorry about that.

**Comment by klajdicaushi** [comment]
@wbarnha Thank you for the quick resolution of the issue!
