### ISSUE TITLE
0.10.22 is broken

### ISSUE THREAD

**Issue by Badgerr** [faust-streaming/faust#620]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

```
$ pip3.9 install faust-streaming==0.10.22
$ python3.9 -c 'import faust; faust.App("new")'
```

## Expected behavior

App instance successfully created.

## Actual behavior

Import error happened.

## Full traceback

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/__init__.py", line 272, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/app/__init__.py", line 2, in <module>
    from .base import App, BootStrategy
  File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/app/base.py", line 46, in <module>
    from mode.utils.contexts import nullcontext
ImportError: cannot import name 'nullcontext' from 'mode.utils.contexts' (/home/badger/.venv/faust/lib/python3.9/site-packages/mode/utils/contexts.py)
```

# Versions

* Python version: 3.9.18
* Faust version: 0.10.22
* Operating system: Ubuntu 22.04 LTS
* Kafka version: n\a
* RocksDB version (if applicable): n\a

**Comment by mehmet-zahid** [comment]
one week ago, it was working(the version of faust maybe was 0.10.22, not sure). but now I am getting this error: 

`Traceback (most recent call last):
  File "/usr/local/bin/faust", line 5, in <module>
    from faust.cli.faust import cli
  File "/usr/local/lib/python3.12/site-packages/faust/cli/faust.py", line 9, in <module>
    from .model import model
  File "/usr/local/lib/python3.12/site-packages/faust/cli/model.py", line 9, in <module>
    from faust.models import registry
  File "/usr/local/lib/python3.12/site-packages/faust/models/__init__.py", line 5, in <module>
    from .record import Record
  File "/usr/local/lib/python3.12/site-packages/faust/models/record.py", line 21, in <module>
    from mode.utils.compat import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'mode.utils.compat' (/usr/local/lib/python3.12/site-packages/mode/utils/compat.py)
`

## Versions
- Python Version: 3.12.2
- Faust version: 0.10.24
- OS: Uubuntu 22.04 LTS

**Comment by mehmet-zahid** [comment]
I resolved my issue .  until the version of 0.11.0, `from mode.utils.compat import OrderedDict` causes error. I realized that it is been removed at the version 0.11.0. I upgraded faust to this version so the issue has been resolved.

**Comment by mehmet-zahid** [comment]
> one week ago, it was working(the version of faust maybe was 0.10.22, not sure). but now I am getting this error:
> 
> `Traceback (most recent call last): File "/usr/local/bin/faust", line 5, in <module> from faust.cli.faust import cli File "/usr/local/lib/python3.12/site-packages/faust/cli/faust.py", line 9, in <module> from .model import model File "/usr/local/lib/python3.12/site-packages/faust/cli/model.py", line 9, in <module> from faust.models import registry File "/usr/local/lib/python3.12/site-packages/faust/models/__init__.py", line 5, in <module> from .record import Record File "/usr/local/lib/python3.12/site-packages/faust/models/record.py", line 21, in <module> from mode.utils.compat import OrderedDict ImportError: cannot import name 'OrderedDict' from 'mode.utils.compat' (/usr/local/lib/python3.12/site-packages/mode/utils/compat.py) `
> ## Versions
> 
>     * Python Version: 3.12.2
> 
>     * Faust version: 0.10.24
> 
>     * OS: Uubuntu 22.04 LTS

I resolved my issue .  until the version of 0.11.0, `from mode.utils.compat import OrderedDict` causes error. I realized that it is been removed at the version 0.11.0. I upgraded faust to this version so the issue has been resolved.

**Comment by mehmet-zahid** [comment]
> ## Checklist
> 
>     * [x]  I have included information about relevant versions
> 
>     * [x]  I have verified that the issue persists when using the `master` branch of Faust.
> 
> 
> ## Steps to reproduce
> 
> ```
> $ pip3.9 install faust-streaming==0.10.22
> $ python3.9 -c 'import faust; faust.App("new")'
> ```
> 
> ## Expected behavior
> 
> App instance successfully created.
> ## Actual behavior
> 
> Import error happened.
> ## Full traceback
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/__init__.py", line 272, in __getattr__
>     module = __import__(object_origins[name], None, None, [name])
>   File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/app/__init__.py", line 2, in <module>
>     from .base import App, BootStrategy
>   File "/home/badger/.venv/faust/lib/python3.9/site-packages/faust/app/base.py", line 46, in <module>
>     from mode.utils.contexts import nullcontext
> ImportError: cannot import name 'nullcontext' from 'mode.utils.contexts' (/home/badger/.venv/faust/lib/python3.9/site-packages/mode/utils/contexts.py)
> ```
> 
> # Versions
> 
>     * Python version: 3.9.18
> 
>     * Faust version: 0.10.22
> 
>     * Operating system: Ubuntu 22.04 LTS
> 
>     * Kafka version: n\a
> 
>     * RocksDB version (if applicable): n\a

Look at this commit : https://github.com/faust-streaming/faust/commit/ed85356874680727695b8c0ccc8130789906a1dc

**Comment by wbarnha** [comment]
`faust-streaming==0.10.22` is not broken, sorry, it was a bad release of `mode-streaming==0.3.6` that has since been yanked. I advise upgrading `mode-streaming` to `0.4.0`.
